import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1 className='text-3xl font-bold underline'>Hello world!</h1>
      <div className='flex items-center space-x-2 text-base'>
        <h4 className='font-semibold text-slate-900'>Contributors</h4>
        <span className='rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-700'>
          204
        </span>
      </div>
      <div className='mt-3 flex -space-x-2 overflow-hidden'>
        <img
          className='inline-block h-12 w-12 rounded-full ring-2 ring-white'
          src='https://images.unsplash.com/photo-1491528323818-fdd1faba62cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80'
          alt=''
        />
        <img
          className='inline-block h-12 w-12 rounded-full ring-2 ring-white'
          src='https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80'
          alt=''
        />
        <img
          className='inline-block h-12 w-12 rounded-full ring-2 ring-white'
          src='https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2.25&w=256&h=256&q=80'
          alt=''
        />
        <img
          className='inline-block h-12 w-12 rounded-full ring-2 ring-white'
          src='https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80'
          alt=''
        />
        <img
          className='inline-block h-12 w-12 rounded-full ring-2 ring-white'
          src='https://images.unsplash.com/photo-1517365830460-955ce3ccd263?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80'
          alt=''
        />
      </div>
      <div className='mt-3 text-sm font-medium'>
        <a href='#' className='text-blue-500'>
          + 198 others
        </a>
      </div>
    </div>
  );
}
